SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `ECE1779_AUTO_SCALER_DB` ;
CREATE SCHEMA IF NOT EXISTS `ECE1779_AUTO_SCALER_DB` DEFAULT CHARACTER SET utf8 ;
USE `ECE1779_AUTO_SCALER_DB` ;

DROP TABLE IF EXISTS `ECE1779_AUTO_SCALER_DB`.`policy`;
CREATE TABLE IF NOT EXISTS `policy` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `cpu_grow_threshold` FLOAT,
    `cpu_shrink_threshold` FLOAT,
    `cpu_grow_ratio` FLOAT,
    `cpu_shrink_ratio` FLOAT,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB;

START TRANSACTION;
USE `ECE1779_AUTO_SCALER_DB`;
INSERT INTO `ECE1779_AUTO_SCALER_DB`.`policy` (`id`, `cpu_grow_threshold`, `cpu_shrink_threshold`, `cpu_grow_ratio`, `cpu_shrink_ratio`) 
VALUES (1, 80, 5, 2, 0.5);

COMMIT;
